name: validate
on: [push, pull_request]
jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18', '20' ]
    name: Node ${{ matrix.node }} test
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Run test
        run: yarn run test
      - uses: cypress-io/github-action@v6
        with:
          start: yarn start-test-server
          wait-on: "http://localhost:8888"
          wait-on-timeout: 5
